In [1]:
import pandas as pd

#Createing data from python list.....
data = [["Arif",90],
        ["Jacob",87],
        ["Jack",48],
        ["Jerry",56]]

#Printing the dataframe...
df = pd.DataFrame(data,columns=["Name","Marks"])
print(df)

    Name  Marks
0   Arif     90
1  Jacob     87
2   Jack     48
3  Jerry     56

In [2]:
import pandas as pd

#Createing data from Dictionary list.....
data = {
    "Name":["Arif","Anas","Junaid"],
    "Course":["BAC","BTECH","PHY EDU"],
    "Year":[2023,2024,2022]
}

df = pd.DataFrame(data)

print(df)

     Name   Course  Year
0    Arif      BAC  2023
1    Anas    BTECH  2024
2  Junaid  PHY EDU  2022

In [3]:
#Createing dataframe with the help of numpy array....
import numpy as np

arr = np.array([[1,90],
                [2,89],
                [3,78]])

data = pd.DataFrame(arr,columns=["Roll","Marks"])
data.index = ["a","b","c"]

print(data)

   Roll  Marks
a     1     90
b     2     89
c     3     78

In [4]:
data = [["Alice",65],
        ["Bob",87],
        ["Charlie",45]]

df = pd.DataFrame(data,columns=["Name","Age"])
print(df)

      Name  Age
0    Alice   65
1      Bob   87
2  Charlie   45

In [5]:
data = {
    "Name":["Alice","Bob","Charlie"],
    "Age":[65,87,45]
}

df = pd.DataFrame(data)
print(df)

      Name  Age
0    Alice   65
1      Bob   87
2  Charlie   45

In [6]:
#read the excel file...
df = pd.read_excel("02.1_createing_dataframes.xlsx")

print(df)

      Name  Roll  Marks
0     Arif     1     96
1  Shubham     2     85
2     Anas     3     75
3      Raj     4     82
4    Gulam     5     56

In [7]:
#read the csv file...
df = pd.read_csv("02.1_createing_dataframes.csv")

print(df)

      Name  Roll  Marks
0     Arif     1     96
1  Shubham     2     85
2     Anas     3     75
3      Raj     4     82
4    Gulam     5     56

In [8]:
#read the csv file...
df = pd.read_csv("02.1_createing_dataframes.csv",usecols=["Name","Roll"])

print(df)

      Name  Roll
0     Arif     1
1  Shubham     2
2     Anas     3
3      Raj     4
4    Gulam     5

In [9]:
#read the json file...
df = pd.read_json("02.1_createing_dataframes.json")

print(df)

   Name    Lang
0  Arif  Python
1  jack    java

In [10]:
#read using url..
df = pd.read_csv("https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv")

In [11]:
df

     total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [12]:
df.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [13]:
df.tail()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

In [14]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    object
 3   smoker      244 non-null    object
 4   day         244 non-null    object
 5   time        244 non-null    object
 6   size        244 non-null    int64
dtypes: float64(2), int64(1), object(4)
memory usage: 13.5+ KB

In [15]:
df.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [16]:
df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [17]:
df.shape

(244, 7)