In [1]:
import pandas as pd

df = pd.read_csv("03.1_data_selection&filtering.csv")

In [2]:
df

                 Actor            Film  Year          Genre  IMDB
0        Shahrukh khan          Pathan  2023         Action   7.2
1          Salman Khan     Tiger Zinda  2017         Action   6.0
2            Amir Khan          Dangal  2016      Biography   8.4
3         Ranbir Kapor       Brahmastr  2022        Fantasy   5.6
4        Ranveer Singh       Padmaavai  2018     Historical   7.0
5   Ayushmann Khuranna       Andhadhun  2018       Thirller   8.3
6         Rajkumar Rao           Stree  2018     Horor Core   7.5
7        Hirtik Roshan             War  2019         Action   6.5
8         Akshay Kumar       Good News  2019         Comedy   7.0
9         Kartik Aryan  Bhool Bhulaiya  2022     Horor Core   5.9
10        Varun Dhawan       Badrinath  2017  Romantic Core   6.1
11       Vicky Kaushal             URI  2019         Action   8.2

In [3]:
print("Type:",type(df["Actor"]))

Type: <class 'pandas.core.series.Series'>

In [4]:
df[["Actor","IMDB"]]

                 Actor  IMDB
0        Shahrukh khan   7.2
1          Salman Khan   6.0
2            Amir Khan   8.4
3         Ranbir Kapor   5.6
4        Ranveer Singh   7.0
5   Ayushmann Khuranna   8.3
6         Rajkumar Rao   7.5
7        Hirtik Roshan   6.5
8         Akshay Kumar   7.0
9         Kartik Aryan   5.9
10        Varun Dhawan   6.1
11       Vicky Kaushal   8.2

In [5]:
df.loc[0]  # First row (by label)

Actor    Shahrukh khan
Film            Pathan
Year              2023
Genre           Action
IMDB               7.2
Name: 0, dtype: object

In [6]:
df.iloc[0]  # First row (by position)

Actor    Shahrukh khan
Film            Pathan
Year              2023
Genre           Action
IMDB               7.2
Name: 0, dtype: object

In [7]:
df.loc[8,"Genre"]

'Comedy'

In [8]:
df.iloc[8,3]

'Comedy'

In [9]:
df.loc[0:3,["Actor","IMDB","Film"]]

           Actor  IMDB         Film
0  Shahrukh khan   7.2       Pathan
1    Salman Khan   6.0  Tiger Zinda
2      Amir Khan   8.4       Dangal
3   Ranbir Kapor   5.6    Brahmastr

In [10]:
df.iloc[0:3,0:3]

           Actor         Film  Year
0  Shahrukh khan       Pathan  2023
1    Salman Khan  Tiger Zinda  2017
2      Amir Khan       Dangal  2016

In [11]:
df.at[0,"Actor"]

'Shahrukh khan'

In [12]:
df.iat[0,0]

'Shahrukh khan'

In [13]:
df[df["IMDB"] > 6]

                 Actor       Film  Year          Genre  IMDB
0        Shahrukh khan     Pathan  2023         Action   7.2
2            Amir Khan     Dangal  2016      Biography   8.4
4        Ranveer Singh  Padmaavai  2018     Historical   7.0
5   Ayushmann Khuranna  Andhadhun  2018       Thirller   8.3
6         Rajkumar Rao      Stree  2018     Horor Core   7.5
7        Hirtik Roshan        War  2019         Action   6.5
8         Akshay Kumar  Good News  2019         Comedy   7.0
10        Varun Dhawan  Badrinath  2017  Romantic Core   6.1
11       Vicky Kaushal        URI  2019         Action   8.2

In [14]:
df[df["IMDB"] > 6]["Actor"]

0          Shahrukh khan
2              Amir Khan
4          Ranveer Singh
5     Ayushmann Khuranna
6           Rajkumar Rao
7          Hirtik Roshan
8           Akshay Kumar
10          Varun Dhawan
11         Vicky Kaushal
Name: Actor, dtype: object

In [16]:
df[(df["IMDB"] > 6) & (df["Year"] > 2018)]

            Actor       Film  Year   Genre  IMDB
0   Shahrukh khan     Pathan  2023  Action   7.2
7   Hirtik Roshan        War  2019  Action   6.5
8    Akshay Kumar  Good News  2019  Comedy   7.0
11  Vicky Kaushal        URI  2019  Action   8.2

In [18]:
df.query("Year > 2018 and IMDB > 6")

            Actor       Film  Year   Genre  IMDB
0   Shahrukh khan     Pathan  2023  Action   7.2
7   Hirtik Roshan        War  2019  Action   6.5
8    Akshay Kumar  Good News  2019  Comedy   7.0
11  Vicky Kaushal        URI  2019  Action   8.2

In [21]:
df.query("Actor == 'Salman Khan'")

         Actor         Film  Year   Genre  IMDB
1  Salman Khan  Tiger Zinda  2017  Action   6.0

In [24]:
df[(df["IMDB"] > 7) & (df["Genre"] == "Action")]

            Actor    Film  Year   Genre  IMDB
0   Shahrukh khan  Pathan  2023  Action   7.2
11  Vicky Kaushal     URI  2019  Action   8.2

In [26]:
df.query("IMDB > 7 and Genre == 'Action'")

            Actor    Film  Year   Genre  IMDB
0   Shahrukh khan  Pathan  2023  Action   7.2
11  Vicky Kaushal     URI  2019  Action   8.2

In [30]:
col = "IMDB"
df.query(f"{col} > 7 and Genre == 'Action'")

            Actor    Film  Year   Genre  IMDB
0   Shahrukh khan  Pathan  2023  Action   7.2
11  Vicky Kaushal     URI  2019  Action   8.2

In [32]:
IMDB_LIMIT = 7
df.query(f"IMDB > @IMDB_LIMIT and Genre == 'Action'")

            Actor    Film  Year   Genre  IMDB
0   Shahrukh khan  Pathan  2023  Action   7.2
11  Vicky Kaushal     URI  2019  Action   8.2

In [34]:
df.query("7 < IMDB < 9")

                 Actor       Film  Year       Genre  IMDB
0        Shahrukh khan     Pathan  2023      Action   7.2
2            Amir Khan     Dangal  2016   Biography   8.4
5   Ayushmann Khuranna  Andhadhun  2018    Thirller   8.3
6         Rajkumar Rao      Stree  2018  Horor Core   7.5
11       Vicky Kaushal        URI  2019      Action   8.2

In [35]:
filtered = df.query("IMDB > 7.5")

In [36]:
filtered

                 Actor       Film  Year      Genre  IMDB
2            Amir Khan     Dangal  2016  Biography   8.4
5   Ayushmann Khuranna  Andhadhun  2018   Thirller   8.3
11       Vicky Kaushal        URI  2019     Action   8.2