In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("04.1_data_cleaning&processing.csv")

In [3]:
df

      Name   Age        City Gender              Emial   Join Date
0    Alice  25.0    New York      F    alice@gmail.com  01-05-2021
1      Bob  30.0  Los Angels      M      bob@gmial.com  15-06-2020
2  Charlie   NaN       Delhi      M  charlie@gmail.com  20-07-2021
3    David  22.0      Mumbai      M    david@gmail.com  12-11-2019
4      NaN  28.0       Delhi      F      eve@gmail.com         NaN
5    Alice  25.0    New York      F    alice@gmail.com  01-05-2021
6    Alice  25.0    New York      F    alice@gmail.com  01-05-2021
7  Charlie   NaN       Delhi      M  charlie@gmail.com  20-07-2021
8  Charlie   NaN       Delhi      M  charlie@gmail.com  20-07-2021

In [4]:
df.isnull()

    Name    Age   City  Gender  Emial  Join Date
0  False  False  False   False  False      False
1  False  False  False   False  False      False
2  False   True  False   False  False      False
3  False  False  False   False  False      False
4   True  False  False   False  False       True
5  False  False  False   False  False      False
6  False  False  False   False  False      False
7  False   True  False   False  False      False
8  False   True  False   False  False      False

In [5]:
df.isnull().sum()

Name         1
Age          3
City         0
Gender       0
Emial        0
Join Date    1
dtype: int64

In [6]:
df.dropna()

    Name   Age        City Gender            Emial   Join Date
0  Alice  25.0    New York      F  alice@gmail.com  01-05-2021
1    Bob  30.0  Los Angels      M    bob@gmial.com  15-06-2020
3  David  22.0      Mumbai      M  david@gmail.com  12-11-2019
5  Alice  25.0    New York      F  alice@gmail.com  01-05-2021
6  Alice  25.0    New York      F  alice@gmail.com  01-05-2021

In [7]:
df.dropna(axis=1)

         City Gender              Emial
0    New York      F    alice@gmail.com
1  Los Angels      M      bob@gmial.com
2       Delhi      M  charlie@gmail.com
3      Mumbai      M    david@gmail.com
4       Delhi      F      eve@gmail.com
5    New York      F    alice@gmail.com
6    New York      F    alice@gmail.com
7       Delhi      M  charlie@gmail.com
8       Delhi      M  charlie@gmail.com

In [8]:
df.fillna(0)

      Name   Age        City Gender              Emial   Join Date
0    Alice  25.0    New York      F    alice@gmail.com  01-05-2021
1      Bob  30.0  Los Angels      M      bob@gmial.com  15-06-2020
2  Charlie   0.0       Delhi      M  charlie@gmail.com  20-07-2021
3    David  22.0      Mumbai      M    david@gmail.com  12-11-2019
4        0  28.0       Delhi      F      eve@gmail.com           0
5    Alice  25.0    New York      F    alice@gmail.com  01-05-2021
6    Alice  25.0    New York      F    alice@gmail.com  01-05-2021
7  Charlie   0.0       Delhi      M  charlie@gmail.com  20-07-2021
8  Charlie   0.0       Delhi      M  charlie@gmail.com  20-07-2021

In [9]:
df["Age"].fillna(df["Age"].mean())

0    25.000000
1    30.000000
2    25.833333
3    22.000000
4    28.000000
5    25.000000
6    25.000000
7    25.833333
8    25.833333
Name: Age, dtype: float64

In [10]:
df.ffill()

      Name   Age        City Gender              Emial   Join Date
0    Alice  25.0    New York      F    alice@gmail.com  01-05-2021
1      Bob  30.0  Los Angels      M      bob@gmial.com  15-06-2020
2  Charlie  30.0       Delhi      M  charlie@gmail.com  20-07-2021
3    David  22.0      Mumbai      M    david@gmail.com  12-11-2019
4    David  28.0       Delhi      F      eve@gmail.com  12-11-2019
5    Alice  25.0    New York      F    alice@gmail.com  01-05-2021
6    Alice  25.0    New York      F    alice@gmail.com  01-05-2021
7  Charlie  25.0       Delhi      M  charlie@gmail.com  20-07-2021
8  Charlie  25.0       Delhi      M  charlie@gmail.com  20-07-2021

In [11]:
df.bfill()

      Name   Age        City Gender              Emial   Join Date
0    Alice  25.0    New York      F    alice@gmail.com  01-05-2021
1      Bob  30.0  Los Angels      M      bob@gmial.com  15-06-2020
2  Charlie  22.0       Delhi      M  charlie@gmail.com  20-07-2021
3    David  22.0      Mumbai      M    david@gmail.com  12-11-2019
4    Alice  28.0       Delhi      F      eve@gmail.com  01-05-2021
5    Alice  25.0    New York      F    alice@gmail.com  01-05-2021
6    Alice  25.0    New York      F    alice@gmail.com  01-05-2021
7  Charlie   NaN       Delhi      M  charlie@gmail.com  20-07-2021
8  Charlie   NaN       Delhi      M  charlie@gmail.com  20-07-2021

In [12]:
df.duplicated()

0    False
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [13]:
df.drop_duplicates()

      Name   Age        City Gender              Emial   Join Date
0    Alice  25.0    New York      F    alice@gmail.com  01-05-2021
1      Bob  30.0  Los Angels      M      bob@gmial.com  15-06-2020
2  Charlie   NaN       Delhi      M  charlie@gmail.com  20-07-2021
3    David  22.0      Mumbai      M    david@gmail.com  12-11-2019
4      NaN  28.0       Delhi      F      eve@gmail.com         NaN

In [14]:
df.duplicated(["Name","Age"])

0    False
1    False
2    False
3    False
4    False
5     True
6     True
7     True
8     True
dtype: bool

In [15]:
df["Name"].str.lower()

0      alice
1        bob
2    charlie
3      david
4        NaN
5      alice
6      alice
7    charlie
8    charlie
Name: Name, dtype: object

In [16]:
df

      Name   Age        City Gender              Emial   Join Date
0    Alice  25.0    New York      F    alice@gmail.com  01-05-2021
1      Bob  30.0  Los Angels      M      bob@gmial.com  15-06-2020
2  Charlie   NaN       Delhi      M  charlie@gmail.com  20-07-2021
3    David  22.0      Mumbai      M    david@gmail.com  12-11-2019
4      NaN  28.0       Delhi      F      eve@gmail.com         NaN
5    Alice  25.0    New York      F    alice@gmail.com  01-05-2021
6    Alice  25.0    New York      F    alice@gmail.com  01-05-2021
7  Charlie   NaN       Delhi      M  charlie@gmail.com  20-07-2021
8  Charlie   NaN       Delhi      M  charlie@gmail.com  20-07-2021

In [17]:
df["City"].str.contains("delhi", case=False)

0    False
1    False
2     True
3    False
4     True
5    False
6    False
7     True
8     True
Name: City, dtype: bool

In [18]:
type(df["City"].str.contains("delhi", case=False))

pandas.core.series.Series

In [19]:
df["City"].str.split()

0      [New, York]
1    [Los, Angels]
2          [Delhi]
3         [Mumbai]
4          [Delhi]
5      [New, York]
6      [New, York]
7          [Delhi]
8          [Delhi]
Name: City, dtype: object

In [20]:
type(df["City"].str.split()[0])

list

In [21]:
df2 = df.dropna().copy()

In [22]:
df2["Age"] = df2["Age"].astype("int32")

In [23]:
df2

    Name  Age        City Gender            Emial   Join Date
0  Alice   25    New York      F  alice@gmail.com  01-05-2021
1    Bob   30  Los Angels      M    bob@gmial.com  15-06-2020
3  David   22      Mumbai      M  david@gmail.com  12-11-2019
5  Alice   25    New York      F  alice@gmail.com  01-05-2021
6  Alice   25    New York      F  alice@gmail.com  01-05-2021

In [24]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, 0 to 6
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Name       5 non-null      object
 1   Age        5 non-null      int32
 2   City       5 non-null      object
 3   Gender     5 non-null      object
 4   Emial      5 non-null      object
 5   Join Date  5 non-null      object
dtypes: int32(1), object(5)
memory usage: 260.0+ bytes

In [25]:
df2.dtypes

Name         object
Age           int32
City         object
Gender       object
Emial        object
Join Date    object
dtype: object

In [26]:
df2

    Name  Age        City Gender            Emial   Join Date
0  Alice   25    New York      F  alice@gmail.com  01-05-2021
1    Bob   30  Los Angels      M    bob@gmial.com  15-06-2020
3  David   22      Mumbai      M  david@gmail.com  12-11-2019
5  Alice   25    New York      F  alice@gmail.com  01-05-2021
6  Alice   25    New York      F  alice@gmail.com  01-05-2021

In [31]:
df2["Age Group"] = df2["Age"].apply(lambda x: "Adult" if x >= 25 else "Minnor")

In [32]:
df2

    Name  Age        City Gender            Emial   Join Date Age Group
0  Alice   25    New York      F  alice@gmail.com  01-05-2021     Adult
1    Bob   30  Los Angels      M    bob@gmial.com  15-06-2020     Adult
3  David   22      Mumbai      M  david@gmail.com  12-11-2019    Minnor
5  Alice   25    New York      F  alice@gmail.com  01-05-2021     Adult
6  Alice   25    New York      F  alice@gmail.com  01-05-2021     Adult

In [34]:
def isminnor(x):
    return "Adult" if x >= 25 else "Minnor"
df2["Age Group"] = df2["Age"].apply(isminnor)

In [35]:
df2

    Name  Age        City Gender            Emial   Join Date Age Group
0  Alice   25    New York      F  alice@gmail.com  01-05-2021     Adult
1    Bob   30  Los Angels      M    bob@gmial.com  15-06-2020     Adult
3  David   22      Mumbai      M  david@gmail.com  12-11-2019    Minnor
5  Alice   25    New York      F  alice@gmail.com  01-05-2021     Adult
6  Alice   25    New York      F  alice@gmail.com  01-05-2021     Adult

In [40]:
gender_map = {"M":"Male","F":"Female","O":"Other"}
df["Gender"] = df["Gender"].map(gender_map)

In [42]:
df

      Name   Age        City  Gender              Emial   Join Date
0    Alice  25.0    New York  Female    alice@gmail.com  01-05-2021
1      Bob  30.0  Los Angels    Male      bob@gmial.com  15-06-2020
2  Charlie   NaN       Delhi    Male  charlie@gmail.com  20-07-2021
3    David  22.0      Mumbai    Male    david@gmail.com  12-11-2019
4      NaN  28.0       Delhi  Female      eve@gmail.com         NaN
5    Alice  25.0    New York  Female    alice@gmail.com  01-05-2021
6    Alice  25.0    New York  Female    alice@gmail.com  01-05-2021
7  Charlie   NaN       Delhi    Male  charlie@gmail.com  20-07-2021
8  Charlie   NaN       Delhi    Male  charlie@gmail.com  20-07-2021

In [48]:
df2["City"] = df2["City"].replace({"Delhi":"New Delhi","Mumbai":"New Mumbai"})

In [49]:
df2

    Name  Age        City  Gender            Emial   Join Date Age Group
0  Alice   25    New York  Female  alice@gmail.com  01-05-2021     Adult
1    Bob   30  Los Angels    Male    bob@gmial.com  15-06-2020     Adult
3  David   22  New Mumbai    Male  david@gmail.com  12-11-2019    Minnor
5  Alice   25    New York  Female  alice@gmail.com  01-05-2021     Adult
6  Alice   25    New York  Female  alice@gmail.com  01-05-2021     Adult