In [1]:
import pandas as pd

In [38]:
df = pd.read_csv("05.1_data_selection&filtering.csv")

In [39]:
df

                 Actor            Film  Year          Genre  IMDB
0        Shahrukh khan          Pathan  2023         Action   7.2
1          Salman Khan     Tiger Zinda  2017         Action   6.0
2            Amir Khan          Dangal  2016      Biography   8.4
3         Ranbir Kapor       Brahmastr  2022        Fantasy   5.6
4        Ranveer Singh       Padmaavai  2018     Historical   7.0
5   Ayushmann Khuranna       Andhadhun  2018       Thirller   8.3
6         Rajkumar Rao           Stree  2018     Horor Core   7.5
7        Hirtik Roshan             War  2019         Action   6.5
8         Akshay Kumar       Good News  2019         Comedy   7.0
9         Kartik Aryan  Bhool Bhulaiya  2022     Horor Core   5.9
10        Varun Dhawan       Badrinath  2017  Romantic Core   6.1
11       Vicky Kaushal             URI  2019         Action   8.2

In [4]:
df.sort_values("Year")

                 Actor            Film  Year          Genre  IMDB
2            Amir Khan          Dangal  2016      Biography   8.4
1          Salman Khan     Tiger Zinda  2017         Action   6.0
10        Varun Dhawan       Badrinath  2017  Romantic Core   6.1
4        Ranveer Singh       Padmaavai  2018     Historical   7.0
5   Ayushmann Khuranna       Andhadhun  2018       Thirller   8.3
6         Rajkumar Rao           Stree  2018     Horor Core   7.5
7        Hirtik Roshan             War  2019         Action   6.5
8         Akshay Kumar       Good News  2019         Comedy   7.0
11       Vicky Kaushal             URI  2019         Action   8.2
3         Ranbir Kapor       Brahmastr  2022        Fantasy   5.6
9         Kartik Aryan  Bhool Bhulaiya  2022     Horor Core   5.9
0        Shahrukh khan          Pathan  2023         Action   7.2

In [5]:
df.sort_values("Year", ascending=False)

                 Actor            Film  Year          Genre  IMDB
0        Shahrukh khan          Pathan  2023         Action   7.2
3         Ranbir Kapor       Brahmastr  2022        Fantasy   5.6
9         Kartik Aryan  Bhool Bhulaiya  2022     Horor Core   5.9
7        Hirtik Roshan             War  2019         Action   6.5
8         Akshay Kumar       Good News  2019         Comedy   7.0
11       Vicky Kaushal             URI  2019         Action   8.2
4        Ranveer Singh       Padmaavai  2018     Historical   7.0
5   Ayushmann Khuranna       Andhadhun  2018       Thirller   8.3
6         Rajkumar Rao           Stree  2018     Horor Core   7.5
1          Salman Khan     Tiger Zinda  2017         Action   6.0
10        Varun Dhawan       Badrinath  2017  Romantic Core   6.1
2            Amir Khan          Dangal  2016      Biography   8.4

In [17]:
df2 = df.sort_values(["Year","IMDB"]).copy()

In [18]:
#df2.reset_index(drop = True, inplace= True)

In [19]:
df2

                 Actor            Film  Year          Genre  IMDB
2            Amir Khan          Dangal  2016      Biography   8.4
1          Salman Khan     Tiger Zinda  2017         Action   6.0
10        Varun Dhawan       Badrinath  2017  Romantic Core   6.1
4        Ranveer Singh       Padmaavai  2018     Historical   7.0
6         Rajkumar Rao           Stree  2018     Horor Core   7.5
5   Ayushmann Khuranna       Andhadhun  2018       Thirller   8.3
7        Hirtik Roshan             War  2019         Action   6.5
8         Akshay Kumar       Good News  2019         Comedy   7.0
11       Vicky Kaushal             URI  2019         Action   8.2
3         Ranbir Kapor       Brahmastr  2022        Fantasy   5.6
9         Kartik Aryan  Bhool Bhulaiya  2022     Horor Core   5.9
0        Shahrukh khan          Pathan  2023         Action   7.2

In [20]:
df2.sort_index()

                 Actor            Film  Year          Genre  IMDB
0        Shahrukh khan          Pathan  2023         Action   7.2
1          Salman Khan     Tiger Zinda  2017         Action   6.0
2            Amir Khan          Dangal  2016      Biography   8.4
3         Ranbir Kapor       Brahmastr  2022        Fantasy   5.6
4        Ranveer Singh       Padmaavai  2018     Historical   7.0
5   Ayushmann Khuranna       Andhadhun  2018       Thirller   8.3
6         Rajkumar Rao           Stree  2018     Horor Core   7.5
7        Hirtik Roshan             War  2019         Action   6.5
8         Akshay Kumar       Good News  2019         Comedy   7.0
9         Kartik Aryan  Bhool Bhulaiya  2022     Horor Core   5.9
10        Varun Dhawan       Badrinath  2017  Romantic Core   6.1
11       Vicky Kaushal             URI  2019         Action   8.2

In [27]:
df2["Rank"] = df2["IMDB"].rank(ascending= False, method= "dense")

In [28]:
df2

                 Actor            Film  Year          Genre  IMDB  Rank
2            Amir Khan          Dangal  2016      Biography   8.4   1.0
1          Salman Khan     Tiger Zinda  2017         Action   6.0   9.0
10        Varun Dhawan       Badrinath  2017  Romantic Core   6.1   8.0
4        Ranveer Singh       Padmaavai  2018     Historical   7.0   6.0
6         Rajkumar Rao           Stree  2018     Horor Core   7.5   4.0
5   Ayushmann Khuranna       Andhadhun  2018       Thirller   8.3   2.0
7        Hirtik Roshan             War  2019         Action   6.5   7.0
8         Akshay Kumar       Good News  2019         Comedy   7.0   6.0
11       Vicky Kaushal             URI  2019         Action   8.2   3.0
3         Ranbir Kapor       Brahmastr  2022        Fantasy   5.6  11.0
9         Kartik Aryan  Bhool Bhulaiya  2022     Horor Core   5.9  10.0
0        Shahrukh khan          Pathan  2023         Action   7.2   5.0

In [41]:
df = df[["Film", "Actor", "Genre", "Year", "IMDB"]]

In [42]:
df

              Film               Actor          Genre  Year  IMDB
0           Pathan       Shahrukh khan         Action  2023   7.2
1      Tiger Zinda         Salman Khan         Action  2017   6.0
2           Dangal           Amir Khan      Biography  2016   8.4
3        Brahmastr        Ranbir Kapor        Fantasy  2022   5.6
4        Padmaavai       Ranveer Singh     Historical  2018   7.0
5        Andhadhun  Ayushmann Khuranna       Thirller  2018   8.3
6            Stree        Rajkumar Rao     Horor Core  2018   7.5
7              War       Hirtik Roshan         Action  2019   6.5
8        Good News        Akshay Kumar         Comedy  2019   7.0
9   Bhool Bhulaiya        Kartik Aryan     Horor Core  2022   5.9
10       Badrinath        Varun Dhawan  Romantic Core  2017   6.1
11             URI       Vicky Kaushal         Action  2019   8.2