In [1]:
import pandas as pd

In [2]:
df = pd.DataFrame({
    "Department":["HR","HR","IT","IT","MARKETING","MARKETING","SALES","SALES"],
    "Team":["A","A","B","B","C","C","D","D"],
    "Gender":["M","F","M","F","M","F","M","F"],
    "Salary":[85, 90, 78, 85, 92, 88, 75, 80],
    "Ages":[23, 25, 30, 22, 28, 26, 21, 27],
    "JoinDate":pd.to_datetime([
        "2020-01-10", "2020-02-15", "2021-03-20", "2021-04-10",
        "2020-05-30", "2020-06-25", "2021-07-15", "2021-08-01"
    ])
})

In [3]:
df.groupby("Department")["Salary"].mean()

Department
HR           87.5
IT           81.5
MARKETING    90.0
SALES        77.5
Name: Salary, dtype: float64

In [4]:
type(df.groupby("Department")["Salary"].mean())

pandas.core.series.Series

In [5]:
df.groupby("Team")["Salary"].sum()

Team
A    175
B    163
C    180
D    155
Name: Salary, dtype: int64

In [6]:
df.groupby("Department")["Salary"].count()

Department
HR           2
IT           2
MARKETING    2
SALES        2
Name: Salary, dtype: int64

In [7]:
df.groupby("Department")["Salary"].min()

Department
HR           85
IT           78
MARKETING    88
SALES        75
Name: Salary, dtype: int64

In [8]:
df.groupby("Team")["Salary"].min()

Team
A    85
B    78
C    88
D    75
Name: Salary, dtype: int64

In [9]:
df.groupby("Department")["Salary"].max()

Department
HR           90
IT           85
MARKETING    92
SALES        80
Name: Salary, dtype: int64

In [10]:
df.groupby("Team")["Salary"].max()

Team
A    90
B    85
C    92
D    80
Name: Salary, dtype: int64

In [11]:
df.groupby("Team")["Salary"].agg(["mean","min","max"])

      mean  min  max
Team
A     87.5   85   90
B     81.5   78   85
C     90.0   88   92
D     77.5   75   80

In [12]:
df.groupby("Team")["Salary"].agg(
    avg_score = "mean",
    min_score = "min",
    max_score = "max"
)

      avg_score  min_score  max_score
Team
A          87.5         85         90
B          81.5         78         85
C          90.0         88         92
D          77.5         75         80

In [13]:
df.groupby("Team")["Salary"].aggregate(
    avg_score = "mean",
    min_score = "min",
    max_score = "max"
)

      avg_score  min_score  max_score
Team
A          87.5         85         90
B          81.5         78         85
C          90.0         88         92
D          77.5         75         80

In [14]:
df["Team_Avg"] = df.groupby("Team")["Salary"].transform("mean")

In [15]:
df

  Department Team Gender  Salary  Ages   JoinDate  Team_Avg
0         HR    A      M      85    23 2020-01-10      87.5
1         HR    A      F      90    25 2020-02-15      87.5
2         IT    B      M      78    30 2021-03-20      81.5
3         IT    B      F      85    22 2021-04-10      81.5
4  MARKETING    C      M      92    28 2020-05-30      90.0
5  MARKETING    C      F      88    26 2020-06-25      90.0
6      SALES    D      M      75    21 2021-07-15      77.5
7      SALES    D      F      80    27 2021-08-01      77.5

In [16]:
df.groupby("Team").filter(lambda x: x["Salary"].mean() > 88)

  Department Team Gender  Salary  Ages   JoinDate  Team_Avg
4  MARKETING    C      M      92    28 2020-05-30      90.0
5  MARKETING    C      F      88    26 2020-06-25      90.0