In [1]:
import pandas as pd

In [2]:
Employee = pd.DataFrame({
    "Emply_Id": [1,2,3],
    "Name": ["Alice","Bob","Charlie"],
    "Dept_Id": [10,20,30] 
})

In [3]:
Employee

   Emply_Id     Name  Dept_Id
0         1    Alice       10
1         2      Bob       20
2         3  Charlie       30

In [4]:
Department = pd.DataFrame({
    "Dept_Id": [10,20,40],
    "Dept_Name": ["HR","Engneering","Marketing"] 
})

In [5]:
Department

   Dept_Id   Dept_Name
0       10          HR
1       20  Engneering
2       40   Marketing

In [7]:
pd.merge(Employee, Department, on = "Dept_Id") #Inner join

   Emply_Id   Name  Dept_Id   Dept_Name
0         1  Alice       10          HR
1         2    Bob       20  Engneering

In [11]:
pd.merge(Employee, Department, on = "Dept_Id", how= "left") #left join

   Emply_Id     Name  Dept_Id   Dept_Name
0         1    Alice       10          HR
1         2      Bob       20  Engneering
2         3  Charlie       30         NaN

In [14]:
pd.merge(Employee, Department, on = "Dept_Id", how= "right") #Right Join

   Emply_Id   Name  Dept_Id   Dept_Name
0       1.0  Alice       10          HR
1       2.0    Bob       20  Engneering
2       NaN    NaN       40   Marketing

In [17]:
pd.merge(Employee, Department, on = "Dept_Id", how="outer") #Outer Join

   Emply_Id     Name  Dept_Id   Dept_Name
0       1.0    Alice       10          HR
1       2.0      Bob       20  Engneering
2       3.0  Charlie       30         NaN
3       NaN      NaN       40   Marketing

In [29]:
df1 = pd.DataFrame({"Name":["Alice","Bob"],"Score":[479,658]})
df2 = pd.DataFrame({"Name":["Charlie","David"],"Age":[45,78]})

In [30]:
df1

    Name  Score
0  Alice    479
1    Bob    658

In [31]:
df2

      Name  Age
0  Charlie   45
1    David   78

In [32]:
pd.concat([df1,df2])

      Name  Score   Age
0    Alice  479.0   NaN
1      Bob  658.0   NaN
0  Charlie    NaN  45.0
1    David    NaN  78.0

In [33]:
pd.concat([df1,df2], axis=1) #Horigentally wise

    Name  Score     Name  Age
0  Alice    479  Charlie   45
1    Bob    658    David   78

In [38]:
df1 = pd.DataFrame({"Id": [1,2]})
df2 = pd.DataFrame({"Score": [90,80]})

Hor_wise = pd.concat([df1,df2], axis = 1) #Column wise

In [39]:
Hor_wise

   Id  Score
0   1     90
1   2     80