In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("09.1_working_with_csv.csv")

In [3]:
df

                 Actor            Film  Year          Genre  IMDB
0        Shahrukh khan          Pathan  2023         Action   7.2
1          Salman Khan     Tiger Zinda  2017         Action   6.0
2            Amir Khan          Dangal  2016      Biography   8.4
3         Ranbir Kapor       Brahmastr  2022        Fantasy   5.6
4        Ranveer Singh       Padmaavai  2018     Historical   7.0
5   Ayushmann Khuranna       Andhadhun  2018       Thirller   8.3
6         Rajkumar Rao           Stree  2018     Horor Core   7.5
7        Hirtik Roshan             War  2019         Action   6.5
8         Akshay Kumar       Good News  2019         Comedy   7.0
9         Kartik Aryan  Bhool Bhulaiya  2022     Horor Core   5.9
10        Varun Dhawan       Badrinath  2017  Romantic Core   6.1
11       Vicky Kaushal             URI  2019         Action   8.2

In [4]:
df = df[df["IMDB"] > 6.0]

In [5]:
df

                 Actor       Film  Year          Genre  IMDB
0        Shahrukh khan     Pathan  2023         Action   7.2
2            Amir Khan     Dangal  2016      Biography   8.4
4        Ranveer Singh  Padmaavai  2018     Historical   7.0
5   Ayushmann Khuranna  Andhadhun  2018       Thirller   8.3
6         Rajkumar Rao      Stree  2018     Horor Core   7.5
7        Hirtik Roshan        War  2019         Action   6.5
8         Akshay Kumar  Good News  2019         Comedy   7.0
10        Varun Dhawan  Badrinath  2017  Romantic Core   6.1
11       Vicky Kaushal        URI  2019         Action   8.2

In [6]:
df.to_csv("09.2_updated_csv.csv")

In [7]:
df.to_csv("09.3_updated_csv.csv", index=False)

In [8]:
df = pd.read_json("09.4_my_json.json")

In [9]:
df

   Id   name                                   address
0   1  Alice   {'city': 'Delhi', 'zipcode': '1100001'}
1   2    Bob  {'city': 'Mumbai', 'zipcode': '4000001'}

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Id       2 non-null      int64
 1   name     2 non-null      object
 2   address  2 non-null      object
dtypes: int64(1), object(2)
memory usage: 180.0+ bytes

In [11]:
data = [
  {"Id":1, "name": "Alice", "address":{"city": "Delhi","zipcode": "1100001"}},
  {"Id":2, "name": "Bob", "address":{"city": "Mumbai","zipcode": "4000001"}}

]

In [12]:
pd.json_normalize(data)

   Id   name address.city address.zipcode
0   1  Alice        Delhi         1100001
1   2    Bob       Mumbai         4000001

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2 entries, 0 to 1
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Id       2 non-null      int64
 1   name     2 non-null      object
 2   address  2 non-null      object
dtypes: int64(1), object(2)
memory usage: 180.0+ bytes